---
- hosts: 192.168.1.233
  gather_facts: no

  tasks:
  - name: CONFIGURE SSH VERSION 2 
    ios_config:
      lines:
        - ip ssh version 2

  - name: SHOW RUN | I SSH 
    ios_command:
      commands:
        - show run | i ssh
    register: after_v2

  - debug: var=after_v2.stdout_lines
